[package]
name = "website"
version = "0.1.0"
authors = ["Jan Kuehle <jkuehle90@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-rt = "1.0.0"
actix-web = "2.0.0"
bytes = "0.5.3"
env_logger = "0.7.1"
github_client = { path = "../packages/github_client" }
hmac = "0.7.1"
influxdb_client = { path = "../packages/influxdb_client" }
listenfd = "0.3.3"
log = "0.4.8"
once_cell = "1.3.1"
reqwest = { version = "0.10.1", features = ["json"] }
secstr = "0.3.2"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.44"
sha-1 = "0.8.2"
stats = { path = "../packages/stats" }
typed-html = "0.2.1"
url = "2.1.1"
