apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghss-influxdb
spec:
  selector:
    matchLabels:
      app: ghss-influxdb
  replicas: 1
  template:
    metadata:
      labels:
        app: ghss-influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb
          env:
            - name: INFLUXDB_DB
              value: db0
            - name: INFLUXDB_USER
              valueFrom:
                secretKeyRef:
                  name: ghss-influxdb
                  key: username
            - name: INFLUXDB_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ghss-influxdb
                  key: password
          ports:
            - containerPort: 8086
          # resources:
          #   limits:
          #     cpu: 100m
          #     memory: 100Mi
          #   requests:
          #     cpu: 100m
          #     memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ghss-influxdb
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8086
  selector:
    app: ghss-influxdb
