apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghss-influxdb
spec:
  selector:
    matchLabels:
      app: ghss-influxdb
  replicas: 1
  template:
    metadata:
      labels:
        app: ghss-influxdb
    spec:
      containers:
        - name: influxdb
          image: influxdb:1.7.9
          env:
            - name: INFLUXDB_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: ghss-influxdb
                  key: admin_username
            - name: INFLUXDB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ghss-influxdb
                  key: admin_password
          ports:
            - containerPort: 8086
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 500Mi
          volumeMounts:
            - name: config
              mountPath: /etc/influxdb/influxdb.conf
              subPath: influxdb.conf
            - name: data
              mountPath: /var/lib/influxdb
      volumes:
        - name: config
          configMap:
            name: ghss-influxdb
        - name: data
          persistentVolumeClaim:
            claimName: ghss-influxdb
